name: publish-package

on: workflow_dispatch

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.x
    - name: Setup Github Source
      run: dotnet nuget add source --username WardenDrew --password ${{ secrets.GITHUB_TOKEN }} --store-password-in-clear-text --name github "https://nuget.pkg.github.com/WardenDrew/index.json"
    - name: Build
      run: dotnet build Simkeys/Simkeys.csproj -c Release
    - name: Pack for publish
      run: dotnet pack Simkeys/Simkeys.csproj -c Release --no-build
    - name: Upload Package
      run: dotnet nuget push "**/*.nupkg" --api-key ${{ secrets.GITHUB_TOKEN }} --source "github"
